# -*- coding: utf-8 -*-
"""4.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GvuGl_svfgTfgLcmydFs9PfnODPn8p54
"""

import numpy as np
import mpmath as mp
import matplotlib.pyplot as plt
from numpy import linalg as LA
import sys 
import sympy as sym

!cp /content/gdrive/MyDrive/CoordGeo/line/line_funcs.py /content
!cp /content/gdrive/MyDrive/CoordGeo/triangle/triangle_funcs.py /content
!cp /content/gdrive/MyDrive/CoordGeo/conics/conics_funcs.py /content 
!cp /content/gdrive/MyDrive/CoordGeo/params.py /content

from mpmath import *
mp.dps = 15; mp.pretty = True

a= 4
x = pi/4
y = pi/6

A = np.array(([0,0]))
B = np.array(([a/mp.tan(x),0]))
D = np.array(([a/mp.tan(y),0]))
E = np.array(([a/mp.tan(y),a]))
C = np.array(([a/mp.tan(x),a]))

x_AB = line_gen(A,B)
x_BC= line_gen(B,C)
x_CA = line_gen(C,A)
x_BD = line_gen(B,D)
x_DE = line_gen(D,E)
x_AE = line_gen(A,E)
x_CE = line_gen(C,E)

plt.plot(x_AB[0,:],x_AB[1,:],label='$AB$')
plt.plot(x_BC[0,:],x_BC[1,:],label='$BC$')
plt.plot(x_CA[0,:],x_CA[1,:],label='$CA$')
plt.plot(x_BD[0,:],x_BD[1,:],label='$BD$')
plt.plot(x_DE[0,:],x_DE[1,:],label='$DE$')
plt.plot(x_AE[0,:],x_AE[1,:],label='$AE$')
plt.plot(x_CE[0,:],x_CE[1,:],label='$CE$')

tri_coords = np.vstack((A,B,C,D,E)).T
plt.scatter(tri_coords[0,:], tri_coords[1,:])
vert_labels = ['A','B','C','D', 'E']
for i, txt in enumerate(vert_labels):
    plt.annotate(txt, # this is the text
                 (tri_coords[0,i], tri_coords[1,i]), # this is the point to label
                 textcoords="offset points", # how to position the text
                 xytext=(0,10), # distance from text to points (x,y)
                 ha='center') # horizontal alignment can be left, right or center

plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')

