# -*- coding: utf-8 -*-
"""4.4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GvuGl_svfgTfgLcmydFs9PfnODPn8p54
"""

import numpy as np
import mpmath as mp
import matplotlib.pyplot as plt
from numpy import linalg as LA
import sys 
import sympy as sym

a = math.pi / 6

a

x = (math.cos(a)+math.sin(a))

y = np.sqrt(2)*math.cos(a)

z = (math.cos(a)-math.sin(a))

w = np.sqrt(2)*math.sin(a)

if z ==w:
  print("Not equal")
else: 
    print("LHS = RHS")