# -*- coding: utf-8 -*-
"""5.5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GvuGl_svfgTfgLcmydFs9PfnODPn8p54
"""

import numpy as np
import mpmath as mp
import matplotlib.pyplot as plt
from numpy import linalg as LA
import sys 
import sympy as sym

a = int(input())
b = int(input())
c = int(input())

A = (1/ (a+b+c))
A

B = (1/a)+(1/b)+(1/c)
B

a = int(input())
b = int(input())
c = int(input())

A = (1/ (a+b+c))
A

B = (1/a)+(1/b)+(1/c)
B

