# -*- coding: utf-8 -*-
"""3.4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GvuGl_svfgTfgLcmydFs9PfnODPn8p54
"""

import numpy as np
import mpmath as mp
import matplotlib.pyplot as plt
from numpy import linalg as LA
import sys 
import sympy as sym

r_1 = 18
h_1 = 32
h_2 = 24

x = (3 * (r_1**2)* h_1)/ (h_2)

r_2 = np.sqrt(x)
r_2

l = np.sqrt(r_2**2 + h_2 **2)
print(l)

