# -*- coding: utf-8 -*-
"""3.5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GvuGl_svfgTfgLcmydFs9PfnODPn8p54
"""

import numpy as np
import mpmath as mp
import matplotlib.pyplot as plt
from numpy import linalg as LA
import sys 
import sympy as sym

r_1 = 22.5
r_2 = 12.5
h = 24

l = np.sqrt((r_1 - r_2)**2 + h **2)
l

area = np.pi * (((r_1 - r_2)*l) + r_2**2)
area

volume = (1/3) * np.pi * (((r_1**2) + (r_2**2)+ (r_1 *r_2)) *h)
print(volume)

