# -*- coding: utf-8 -*-
"""circlesandsectors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GvuGl_svfgTfgLcmydFs9PfnODPn8p54
"""


import numpy as np
import mpmath as mp
import matplotlib.pyplot as plt
from numpy import linalg as LA
import sys

sys.path.insert(0, '/Users/gvv/Desktop/CoordGeo')        #path to my scripts

#local imports
from line.funcs import *
from triangle.funcs import *
from conics.funcs import circ_gen


from mpmath import *
mp.dps = 15; mp.pretty = True

r = 7
theta1 = pi/6
theta2 = pi/3
theta3 = pi/2
x = pi/3
y = 2*pi/9
z = 4*pi/9
e1 = np.array(([1,0]))
e2 = np.array(([0,1]))

O = np.array(([0,0])) #centre
A = r*e1
B = np.array(([r*mp.cos(x),-r*mp.sin(x)]))
C = -r*e2
D = np.array(([r*mp.cos(x+y+theta1),-r*mp.sin(x+y+theta1)]))
F = r*e2
E = np.array(([r*mp.cos(z+theta3),r*mp.sin(z+theta3)]))

xOA = line_gen(O,A)
xOB = line_gen(O,B)
xOC = line_gen(O,C)
xOD = line_gen(O,D)
xOE = line_gen(O,E)
xOF = line_gen(O,F)

x_circ= circ_gen(O,r)

plt.plot(xOA[0,:],xOA[1,:],label='$OA$')
plt.plot(xOB[0,:],xOB[1,:],label='$OB$')
plt.plot(xOC[0,:],xOC[1,:],label='$OC$')
plt.plot(xOD[0,:],xOD[1,:],label='$OD$')
plt.plot(xOE[0,:],xOE[1,:],label='$OE$')
plt.plot(xOF[0,:],xOF[1,:],label='$OF$')
plt.plot(x_circ[0,:],x_circ[1,:],label='$Circle$')
tri_coords = np.vstack((A,B,C,D,E,F,O)).T
plt.scatter(tri_coords[0,:], tri_coords[1,:])
vert_labels = ['A','B','C','D','E','F','O']
for i, txt in enumerate(vert_labels):
    plt.annotate(txt, # this is the text
                 (tri_coords[0,i], tri_coords[1,i]), # this is the point to label
                 textcoords="offset points", # how to position the text
                 xytext=(0,10), # distance from text to points (x,y)
                 ha='center') # horizontal alignment can be left, right or center

plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal') 
plt.show()

