# -*- coding: utf-8 -*-
"""2.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GvuGl_svfgTfgLcmydFs9PfnODPn8p54
"""

No_of_faces = 6
No_of_faces_A_on_a_die = 3 
No_of_faces_B_on_a_die = 2

x = (No_of_faces_A_on_a_die / No_of_faces)
y = (No_of_faces_B_on_a_die / No_of_faces)

print("The probability of A is:", x)
print("The probability of B is:", y)

