# -*- coding: utf-8 -*-
"""2.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GvuGl_svfgTfgLcmydFs9PfnODPn8p54
"""

A = [3,4,4,4,5,5,6,6,6,7]

len(A)

def mean(list):
  return ((sum(list))/len(list))

mean(A)

def countElement(sample_list, element):
	return sample_list.count(element)

x = countElement(A,5)

x

print("Probability that a number selected at random from the numbers A will be their mean is:", (x/len(A)))

