# -*- coding: utf-8 -*-
"""2.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GvuGl_svfgTfgLcmydFs9PfnODPn8p54
"""

import pandas as pd

df = pd.DataFrame({"Class": ['10-14', '14-18', '18-22', '22-26', '26-30', '30-34','34-38'],
                   "Frequency": [8, 6, 11, 20, 25, 22, 10]})

df

#defining terms for calculations
l=26
f_0 = 20
f_1 = 25
f_2 = 22
h = 4

mode = l+((f_1 - f_0)/(2*f_1-f_0-f_2))*h

mode

