# -*- coding: utf-8 -*-
"""2.4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GvuGl_svfgTfgLcmydFs9PfnODPn8p54
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame({"Class": ['0-10', '10-20', '20-30', '30-40', '40-50', '50-60', '60-70'],
                   "Frequency": [5, 15, 20, 23, 17, 11, 9],
                   "Cummlative": [5,20,40,63,80,91,100],
                   "Upper_limit": [10,20,30,40,50,60,70]})

df

y = df["Cummlative"] 
x = df["Upper_limit"]

plt.plot(df["Upper_limit"], df["Cummlative"], '-')
plt.axhline(y=50, xmin=0, xmax=0.415)
plt.axvline(x=34.4, ymin=0, ymax=0.48)
plt.xlabel("Upper Limit")  # add X-axis label
plt.ylabel("Cummutalive Frequency")  # add Y-axis label
plt.title("Cummulative Freqeuncy vs Upper Limit")  # add title
plt.show()

