# -*- coding: utf-8 -*-
"""1.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GvuGl_svfgTfgLcmydFs9PfnODPn8p54
"""

a = 15
d= -3
a_n = 0

n = ((a_n - a)/d)+1
print("The value of n is:",n)

