# -*- coding: utf-8 -*-
"""1.5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GvuGl_svfgTfgLcmydFs9PfnODPn8p54
"""

def hcf(a,b):
     
    if (a == 0):
        return b
    if (b == 0):
        return a

    if (a == b):
        return a
 
    if (a > b):
        return hcf(a-b, b)
    return hcf(a, b-a)

a = 612
b =1314

if(hcf(a, b)):
    print('HCF of', a, 'and', b, 'is', hcf(a, b))
else:
    print('not found')

