# -*- coding: utf-8 -*-
"""1.6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GvuGl_svfgTfgLcmydFs9PfnODPn8p54
"""

import numpy as np

x = 5 - 3*np.sqrt(2)
print(x)